name: ApplicationName
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.12.1
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: 
      - assets/
  fonts:
  - family : Mulish
    fonts:
    - asset: assets/fonts/Mulish-Bold.ttf
      weight: 700
